In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
print(torch.__version__)

2.1.2+cpu


# Intro to tensor


## Creating Tensor

In [3]:
scalar= torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get the tensor as an Python int
scalar.item()

7

In [6]:
# Vector
vector= torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim # Dimension like how many pair of closing bracket

1

In [8]:
vector.shape # It is like 2 elements

torch.Size([2])

In [9]:
# MATRIX
MATRIX= torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR= torch.tensor([[[1,2,3],
                       [3,6,9],
                       [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0][1]

tensor([3, 6, 9])

## Random tensor

Why random tensor?

Random tensor are important because the way many NN learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

`Start with random number -> look at data -> update random numbers -> look at data -> update random numbers`

In [16]:
# Create random tensor of size (3,4)
random_tensor= torch.rand(3, 4)
random_tensor

tensor([[0.6435, 0.7361, 0.9165, 0.3669],
        [0.5531, 0.1920, 0.6009, 0.1577],
        [0.5215, 0.1490, 0.2228, 0.6155]])

In [17]:
# Create random tensor with similar shape to an image tensor
random_image_size_tensor= torch.rand(size= (224, 224, 3)) # height, width, colour channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and Ones

In [18]:
# Create a tensor of all zero
zeros= torch.zeros(size= (3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
# Create tensor of all ones
ones= torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## Creating range of tensors

In [20]:
one_to_ten= torch.arange(start= 1, end= 10, step= 1)
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
# Creating tensor like
ten_zeros= torch.zeros_like(input= one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

**Note**: Tensor datatypes is one of the big 3 errors we'll run into with PyTorch & Deep Learning

1. Tensor not right datatype `tensor.dtype`
1. Tensor not right shape `tensor.shape`
1. Tensors not on the right device `tensor.device`

Datatype: https://pytorch.org/docs/stable/tensors.html

In [22]:
float_32_tensor= torch.tensor([3.0, 6.0, 9.0],
                              dtype= None, # What datatype is the tensor (e.g. float32 or float16)
                              device= None, # We cannot do operation on tensor with 2 different device
                              requires_grad= False) # Whether or not to track gradients with this tensor operation
# 3 most important parameter when creating tensor
float_32_tensor

tensor([3., 6., 9.])

In [23]:
float_32_tensor.dtype # Default is float32

torch.float32

In [24]:
float_16_tensor= float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [25]:
test= float_32_tensor * float_16_tensor
test, test.dtype

(tensor([ 9., 36., 81.]), torch.float32)

In [26]:
int_32_tensor= torch.tensor([3, 6, 9])
int_32_tensor

tensor([3, 6, 9])

In [27]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [28]:
# Getting information from tensor
some_tensor= torch.rand(3, 4)
some_tensor

tensor([[0.6758, 0.9805, 0.9950, 0.5441],
        [0.4062, 0.7299, 0.4070, 0.6844],
        [0.0780, 0.2148, 0.4079, 0.0714]])

In [29]:
# Find details about tensor
print(some_tensor)
print(f'\nDatatype of tensor: {some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Device of tensor: {some_tensor.device}')

tensor([[0.6758, 0.9805, 0.9950, 0.5441],
        [0.4062, 0.7299, 0.4070, 0.6844],
        [0.0780, 0.2148, 0.4079, 0.0714]])

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


## Manipulating tensors

Tensor operation:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [30]:
# Create a tensor
tensor= torch.tensor([1, 2, 3])
tensor+10

tensor([11, 12, 13])

In [31]:
tensor-10

tensor([-9, -8, -7])

In [32]:
tensor*5
# torch.mul(tensor, 5) same

tensor([ 5, 10, 15])

In [33]:
tensor/2
# torch.div(tensor, 2) same

tensor([0.5000, 1.0000, 1.5000])

In [34]:
# Element wise multiplication
tensor*tensor

tensor([1, 4, 9])

In [35]:
torch.matmul(tensor, tensor)

tensor(14)

In [36]:
# Checking time

value= 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

tensor(14)

In [37]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 55 µs, sys: 11 µs, total: 66 µs
Wall time: 69.6 µs


tensor(14)

## Shape errors

In [38]:
# Shapes for matrix multiplication
tensor_A= torch.tensor([[1,2],
                        [3, 4],
                        [5, 6]])
tensor_B= torch.tensor([[7, 10],
                        [8, 11],
                        [9, 12]])

torch.mm(tensor_A, tensor_B.T) #torch.mm == torch.matmul # It will raise error


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding min, max, mean, sum, etc

In [39]:
x= torch.arange(0, 100, 10)
# Find min
print(torch.min(x))

tensor(0)


In [40]:
print(torch.max(x))

tensor(90)


In [41]:
print(torch.mean(x.type(torch.float32))), x.type(torch.float32).mean()

tensor(45.)


(None, tensor(45.))

In [42]:
# Finding sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [43]:
# Finding positional mean and max, just like indexing
x.argmin(), x.argmax()

(tensor(0), tensor(9))

## Reshaping, stacking, squeezing, and unsqueezing tensor

- Reshaping: reshapes an input tensor to a defined shape

- View: Return a view of an input tensor of certain shape but keep the same memory as the original tensor

- Stacking: Combine multiple tensors on top each other (vstack) or side by side (hstack)

- Squeeze: removes all `1` dimensions from a tensor

- Unsqueeze: add a `1` dimension to a target tensor

- Permute: return a view of the input with dimensions permuted (swapped) in a certain way

In [44]:
import torch
x= torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [45]:
# Add an extra dimension
# x_reshaped= x.reshape(1, 7) # This will produce an error
x_reshaped= x.reshape(1, 9) # This will not produce an error
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [46]:
x_reshaped= x.reshape(1, 9) # This will not produce an error
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [47]:
# Change the view
z= x.view(1, 9) # REMEMBER THAT Z SHARE THE SAME MEMORY AS X, CHANGING X ALSO CHANGING Z, VICE VERSA
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [48]:
z[:, 0]= 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [49]:
# Stack tensors on top of each other
x_stacked= torch.stack([x, x, x, x], dim= 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [50]:
# torch.squeeze() - Remove all single dimension target from a target vector
print(f"Previous tensor: {x_reshaped}")
print(f"\nPrevious shape: {x_reshaped.shape}")
print('='*20)

# Remove extra dimension from x_reshaped
x_squeezed= x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"\nNew shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

New shape: torch.Size([9])


In [51]:
# Unsqueeze
# torch.unsqueeze() - Adds a single dimension to a target tensor at a specific dimension
print(f'Previous target: {x_squeezed}')
print(f'Previous shape: {x_squeezed.shape}')

# Add extra dim with unsqueeze
x_unsqueezed= x_squeezed.unsqueeze(dim= 0)
print(f'\nNew tensor: {x_unsqueezed}')
print(f'New shape: {x_unsqueezed.shape}')

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [52]:
# torch.permute - rearranges the dimensions of a target tensor at a specified order
# Remember that it returns a view of the original tensor input, with its dimension permuted

# Commonly used in images
x_original= torch.rand(size= (224, 224, 3)) # [Height, width, color_channel]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted= x_original.permute(2, 0, 1) # Shifts axis 0->1, 1-> 2, 2-> 0
print(f'Previous shape: {x_original.shape}')
print(f'New shape: {x_permuted.shape}') # [color_channel, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing (Selecting data from tensors)
Indexing with torch is similar to numpy

In [53]:
import torch
x= torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [54]:
# Lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [55]:
# Index on the middle bracket (dim= 1)
x[0][0]

tensor([1, 2, 3])

In [56]:
# Lets index on the most inner bracket(last dimension)
x[0][0][1]

tensor(2)

In [57]:
# We can use ':' to select 'all' of a target dimension
x[:, :, 1]

tensor([[2, 5, 8]])

## PyTorch tensors & Numpy
Numpy is a popular scientific Python numerical computing library.

* Data in numpy, want in Pytorch tensor -> `torch.from_numpy(ndarray)`
* Pytorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [58]:
# Numpy array to tensor
import torch
import numpy as np

array= np.arange(1.0, 8.0)
tensor= torch.from_numpy(array) # Remember thaat when converting from np-> torch, pytorch reflect np default dtype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [59]:
array.dtype

dtype('float64')

In [60]:
tensor.dtype

torch.float64

In [61]:
# Change the value of the array
array= array+ 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [62]:
# Tensor to np array
tensor= torch.ones(7)
numpy_tensor= tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [63]:
# Change the tensor, what happens to `numpy_tensor`
tensor= tensor+ 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (Trying to take random out of random)

In short, how NN works:

* `start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks, and Pytorch, comes the concept of a **random seed**.

What it does, is 'flavour' the randomness.

In [64]:
import torch

random_tensor_A= torch.rand(3, 4)
random_tensor_B= torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.4955, 0.3656, 0.7584, 0.6195],
        [0.2204, 0.9374, 0.8312, 0.7930],
        [0.3078, 0.7792, 0.7825, 0.3025]])
tensor([[0.2951, 0.3823, 0.7993, 0.8043],
        [0.3769, 0.1312, 0.2787, 0.0678],
        [0.9504, 0.0052, 0.9177, 0.7741]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [65]:
# Creating some random, but reproducible tensor

# Setting the seed
RANDOM_SEED= 42

torch.manual_seed(RANDOM_SEED) # When using manual seed, only works for one block of code
random_tensor_C= torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED) # If we dont put this here, the RANDOM_SEED only affect C, while D is not
random_tensor_D= torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resources:
* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Pseudorandomness#:~:text=A%20pseudorandom%20sequence%20of%20numbers,completely%20deterministic%20and%20repeatable%20process.

## Running tensors and PyTorch Objects on the GPUs (and making faster computation)

GPU = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything good.

In [66]:
# How to check if available GPU
import torch
torch.cuda.is_available()

False

For torch, since it is capable of running compute on the GPU or CPU, it is best practice to setup device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html

E.g. run on GPU if available, else default to CPU

In [67]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [68]:
# Count number of devices
torch.cuda.device_count()

0

In [69]:
## Putting tensors (and models) on the GPU
tensor= torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [70]:
# Move tensor to GPU (if available)
tensor_on_gpu= tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

In [71]:
# if tensor on GPU, cannot transform to np
# tensor_on_gpu.numpy() # This will error

# Call this first
# tensor_back_on_cpu= tensor_on_gpu.cpu().numpy()
